/*
 * PharmaTrace Supply Chain Information Network API
 *
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * API version: 0.0.1
 * Contact: api@pharmatrace.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type LegalTxTerms struct {
	// GMT, Unix Epoch
	TimestampValidFrom int64 `json:"timestamp_valid_from,omitempty"`
	// GMT, Unix Epoch
	TimestampValidUntil int64 `json:"timestamp_valid_until,omitempty"`
	// tolerance window for transactions that begin but do not finish under the governance of these terms (in ms)
	ValidityTolerance int64 `json:"validity_tolerance,omitempty"`
	// unique id hash of the transaction terms and conditions
	TermsId string `json:"terms_id,omitempty"`
	// optional version mark of the terms
	TermsVersion string `json:"terms_version,omitempty"`
	// optional link to the previous version of these terms
	TermsIdPreviousVersion string `json:"terms_id_previous_version,omitempty"`
	// text of the terms and conditions
	TermsText string `json:"terms_text,omitempty"`
	// ISO language code, e.g. en_us
	Language string `json:"language,omitempty"`
	// legislation enforcing these terms
	Legislation string `json:"legislation,omitempty"`
}
