/*
 * PharmaTrace Supply Chain Information Network API
 *
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * API version: 0.0.1
 * Contact: api@pharmatrace.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Container struct {
	// Unique identifier representing a specific container.
	ContainerId string `json:"container_id,omitempty"`
	// EPC code
	EpcCode string `json:"epc_code,omitempty"`
	// Serialization label.
	Label string `json:"label,omitempty"`
	// barcode on container. Normally equal to container id.
	Barcode string `json:"barcode,omitempty"`
	// RFID of RF tracking label on conatiner.
	RfId string `json:"rf_id,omitempty"`
	// quantity of product in container.
	Quantity float32 `json:"quantity,omitempty"`
	// Unit for quantity measurement.
	Unit string `json:"unit,omitempty"`
	// Location id of last tracked locaction.
	CurrentLocationId string `json:"current_location_id,omitempty"`
	// stakeholder id of the last tracked owner of the container.
	OwnerStakeholderId string `json:"owner_stakeholder_id,omitempty"`
	// id of the parent container or null.
	ParentContainerId string `json:"parent_container_id,omitempty"`
}
