/*
 * PharmaTrace Supply Chain Information Network API
 *
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * API version: 0.0.1
 * Contact: api@pharmatrace.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Stakeholder struct {
	// unique official register entry, e.g. Handelsregistereintrag, court number, ...
	TradeId string `json:"trade_id,omitempty"`
	// type of the official register that has issued the trade id
	TradeIdType string `json:"trade_id_type,omitempty"`
	// display name visible to other network members
	DisplayName string `json:"display_name,omitempty"`
	// one of Manufacturer, Distributor, Pharmacy, Regulator, Hospital, MedicalPractice, CareProvider, DisposalFirm, Insurance, Patient, LawEnforcement
	StakeholderRole string `json:"stakeholder_role,omitempty"`
	// id of the main wallet, which the stakeholder uses for PT token transactions with other stakeholders
	WalletId string `json:"wallet_id,omitempty"`
}
