/*
 * PharmaTrace Supply Chain Information Network API
 *
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * API version: 0.0.1
 * Contact: api@pharmatrace.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Pharmaceutical struct {
	// Either gtin or synthetical for precision medicine.
	PharmaceuticalId string `json:"pharmaceutical_id,omitempty"`
	// Global trade item number (GS1)
	Gtin string `json:"gtin,omitempty"`
	// Manufacturers official name of the pharmaceutical product.
	TradeName string `json:"trade_name,omitempty"`
	// EAN code.
	EanCode string `json:"ean_code,omitempty"`
	// Manufaturer id
	ManufacturerId string `json:"manufacturer_id,omitempty"`
	// Image URL representing the product.
	Image string `json:"image,omitempty"`
}
