/*
 * PharmaTrace Supply Chain Information Network API
 *
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * API version: 0.0.1
 * Contact: api@pharmatrace.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Global system message from PT node operators / Newsfeed
type SystemInformation struct {
	// Unique identifier for the system information.
	Uuid string `json:"uuid,omitempty"`
	// Iso Language code, e.g. en_us.
	Language string `json:"language,omitempty"`
	// Message header.
	Header string `json:"header,omitempty"`
	// message body.
	Message string `json:"message,omitempty"`
}
